config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "page_one", to: "welcome#page_one"
  get "page_two", to: "welcome#page_two"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def page_one
  end

  def page_two
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Appcues Turbolinks Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application" %>

    <script>
      document.addEventListener("turbolinks:load", () => {
        console.log("Turbolinks page loaded")

        window.Appcues.identify("123456789", {testUser: true})

        if (!document.documentElement.hasAttribute("data-turbolinks-preview")) {
          window.Appcues.page();
        }
      })
    </script>

    <script type="text/javascript">
      window.AppcuesSettings = {
        enableURLDetection: true,
        customContainer: '.appcues-wrapper'
      };
    </script>
    <script src="//fast.appcues.com/<%= Rails.application.credentials.appcues_id %>.js"></script>
  </head>

  <body>
    <h1>Appcues standalone turbolinks test</h1>

    <%= link_to "Page one", page_one_path %>
    <%= link_to "Page two", page_two_path %>

    <%= yield %>

    <div id="test" data-turbolinks-permanent>
      <div class='appcues-wrapper'></div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
An index page

app/views/welcome/page_one.html.erb
<h2>Page one</h2>

app/views/welcome/page_two.html.erb
<h2>Page two</h2>